### ISSUE TITLE
Modify the broken down waveform

### ISSUE THREAD

**Issue by Sriram-Y** [Sriram-Y/final-project-assignment-audio-eq-driver#12]
The second stage of the core application is where we adjust the amplitude of the frequencies after the raw waveform has been broken down.

DoD: Have functions that can control the properties of the simpler waves.

Blockers: #11

**Comment by sota6640** [comment]
modify_band() to process the six frequency bands of audio with customizable effects including gain control, added distortion. Each band is processed sample by sample. Clipping protection for overflow cases.
