### ISSUE TITLE
Output the resulting audio through the ALSA driver

### ISSUE THREAD

**Issue by Sriram-Y** [Sriram-Y/final-project-assignment-audio-eq-driver#15]
Clean output without artifacts, loss of data, and the correct modifications

DoD: Able to listen to the audio after it has been modified.

**Comment by sota6640** [comment]
Playback mode accurately outputting the modified mp3 through the speakers connected to the 3.5 mm audio jack. Loopback is set for modes (0,0) for playback of the original audio and (1,0) for capture using application. Playback stream enabled for hw:1:0 sound card to allow modified audio through the speakers.
