### ISSUE TITLE
EQ Control Interface

### ISSUE THREAD

**Issue by Sriram-Y** [Sriram-Y/final-project-assignment-audio-eq-driver#16]
An interface or configuration file that can be edited on the fly. This allows the user to be able to control the output as their audio is playing.

DoD: We should be able to read a user-made configuration file. This file will contain data about how much each band should be amplified.

**Comment by sota6640** [comment]
gains.txt (a user configurable text file) for constant values for each band, along with an EXPORT define if the user wants to encode the output into an .mp3 file
